FROM debian:11
MAINTAINER ROBERTA SOLIMAN
USER root
RUN apt-get update && apt-get install -y \ 
    lynis \
    libpam-tmpdir \
    apt-listbugs \
    apt-listchanges \
    needrestart \
    debsecan \
    debsums \
    fail2ban \
    net-tools \
    busybox-syslogd \
    nano \
    rkhunter \
    procps \
    efibootmgr \
    ssh \
    acct \
    apt-transport-https \
    host \
    gpg 
RUN rm -rf /etc/ssh/sshd_config
ADD sshd_config /etc/ssh/
RUN rm -rf /etc/profile
ADD profile etc/
RUN cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
RUN sshd -T
RUN /etc/init.d/ssh restart
RUN sysctl -a > /tmp/sysctl-defaults.conf 
ADD 80-lynis.conf /etc/sysctl.d/
RUN wget https://cisofy.com/files/cisofy-software.pub \
    gpg --import cisofy-software.pub \
    gpg --list-keys --fingerprint \
    host -t txt cisofy-software-key.cisofy.com

RUN mkdir /var/run/sshd \
    chmod 0755 /var/run/sshd

RUN sshd -T
RUN sysctl --system
RUN cp -v /usr/share/systemd/tmp.mount /etc/systemd/system/ \
    systemctl enable tmp.mount
RUN wget -O - https://packages.cisofy.com/keys/cisofy-software-public.key | apt-key add - \
    echo "deb https://packages.cisofy.com/community/lynis/deb/ stable main" | tee /etc/apt/sources.list.d/cisofy-lynis.list

RUN echo "deb http://deb.debian.org/debian buster-backports main" |  tee -a /etc/apt/sources.list \
    apt -t buster-backports upgrade -y -y \
    apt-get install linux-image-5.10.0-8-amd64 -y
ENTRYPOINT ["/etc/lynis"]
CMD ["--version"]


